In [1]:
pip install yfinance

Requirement already satisfied: yfinance in c:\python311\lib\site-packages (0.2.33)
Requirement already satisfied: pandas>=1.3.0 in c:\python311\lib\site-packages (from yfinance) (2.1.4)
Requirement already satisfied: numpy>=1.16.5 in c:\users\aswan\appdata\roaming\python\python311\site-packages (from yfinance) (1.26.2)
Requirement already satisfied: requests>=2.31 in c:\users\aswan\appdata\roaming\python\python311\site-packages (from yfinance) (2.31.0)
Requirement already satisfied: multitasking>=0.0.7 in c:\python311\lib\site-packages (from yfinance) (0.0.11)
Requirement already satisfied: lxml>=4.9.1 in c:\python311\lib\site-packages (from yfinance) (4.9.3)
Requirement already satisfied: appdirs>=1.4.4 in c:\python311\lib\site-packages (from yfinance) (1.4.4)
Requirement already satisfied: pytz>=2022.5 in c:\python311\lib\site-packages (from yfinance) (2023.3.post1)
Requirement already satisfied: frozendict>=2.3.4 in c:\python311\lib\site-packages (from yfinance) (2.3.10)
Requirement already satisfied: peewee>=3.16.2 in c:\python311\lib\site-packages (from yfinance) (3.17.0)
Requirement already satisfied: beautifulsoup4>=4.11.1 in c:\users\aswan\appdata\roaming\python\python311\site-packages (from yfinance) (4.12.2)
Requirement already satisfied: html5lib>=1.1 in c:\python311\lib\site-packages (from yfinance) (1.1)
Requirement already satisfied: soupsieve>1.2 in c:\users\aswan\appdata\roaming\python\python311\site-packages (from beautifulsoup4>=4.11.1->yfinance) (2.5)
Requirement already satisfied: six>=1.9 in c:\users\aswan\appdata\roaming\python\python311\site-packages (from html5lib>=1.1->yfinance) (1.16.0)
Requirement already satisfied: webencodings in c:\python311\lib\site-packages (from html5lib>=1.1->yfinance) (0.5.1)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\aswan\appdata\roaming\python\python311\site-packages (from pandas>=1.3.0->yfinance) (2.8.2)
Requirement already satisfied: tzdata>=2022.1 in c:\python311\lib\site-packages (from pandas>=1.3.0->yfinance) (2023.3)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\aswan\appdata\roaming\python\python311\site-packages (from requests>=2.31->yfinance) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\aswan\appdata\roaming\python\python311\site-packages (from requests>=2.31->yfinance) (3.6)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\aswan\appdata\roaming\python\python311\site-packages (from requests>=2.31->yfinance) (2.1.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\aswan\appdata\roaming\python\python311\site-packages (from requests>=2.31->yfinance) (2023.11.17)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 23.2.1 -> 23.3.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score
import matplotlib.pyplot as plt
import seaborn as sns
import yfinance as yf

In [3]:
def fetch_stock_data(symbol, start_date, end_date):
    data = yf.download(symbol, start=start_date, end=end_date)
    return data

symbol = "AAPL"
start_date = "2022-01-01"
end_date = "2023-01-01"

stock_data = fetch_stock_data(symbol, start_date, end_date)

[*********************100%%**********************]  1 of 1 completed

In [4]:
stock_data

,Open,High,Low,Close,Adj Close,Volume
Date,,,,,,
2022-01-03,177.830002,182.880005,177.710007,182.009995,179.953873,104487900
2022-01-04,182.630005,182.940002,179.119995,179.699997,177.669983,99310400
2022-01-05,179.610001,180.169998,174.639999,174.919998,172.943985,94537600
2022-01-06,172.699997,175.300003,171.639999,172.000000,170.056992,96904000
2022-01-07,172.889999,174.139999,171.029999,172.169998,170.225052,86709100
...,...,...,...,...,...,...
2022-12-23,130.919998,132.419998,129.639999,131.860001,131.127060,63814900
2022-12-27,131.380005,131.410004,128.720001,130.029999,129.307236,69007800
2022-12-28,129.669998,131.029999,125.870003,126.040001,125.339409,85438400
2022-12-29,127.989998,130.479996,127.730003,129.610001,128.889572,75703700
2022-12-30,128.410004,129.949997,127.430000,129.929993,129.207779,77034200

In [5]:
df = pd.DataFrame({'Date': stock_data.index, 'Price': stock_data.values})

ValueError: Per-column arrays must each be 1-dimensional

In [ ]:
df

          Date       Price
0   2022-01-03  179.953873
1   2022-01-04  177.669983
2   2022-01-05  172.943985
3   2022-01-06  170.056961
4   2022-01-07  170.225052
..         ...         ...
246 2022-12-23  131.127060
247 2022-12-27  129.307251
248 2022-12-28  125.339409
249 2022-12-29  128.889572
250 2022-12-30  129.207779

[251 rows x 2 columns]

90